config/routes.rb
StreetApp::Application.routes.draw do
  resources :parking_restrictions

  resources :parking_spots

  root 'parking_spots#index'

end

app/models/parking_restriction.rb
class ParkingRestriction < ActiveRecord::Base
end

app/models/parking_spot.rb
class ParkingSpot < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/parking_restrictions_controller.rb
class ParkingRestrictionsController < ApplicationController
  before_action :set_parking_restriction, only: [:show, :edit, :update, :destroy]

  # GET /parking_restrictions
  # GET /parking_restrictions.json
  def index
    @parking_restrictions = ParkingRestriction.all
  end

  # GET /parking_restrictions/1
  # GET /parking_restrictions/1.json
  def show
  end

  # GET /parking_restrictions/new
  def new
    @parking_restriction = ParkingRestriction.new
  end

  # GET /parking_restrictions/1/edit
  def edit
  end

  # POST /parking_restrictions
  # POST /parking_restrictions.json
  def create
    @parking_restriction = ParkingRestriction.new(parking_restriction_params)

    respond_to do |format|
      if @parking_restriction.save
        format.html { redirect_to @parking_restriction, notice: 'Parking restriction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parking_restriction }
      else
        format.html { render action: 'new' }
        format.json { render json: @parking_restriction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_restrictions/1
  # PATCH/PUT /parking_restrictions/1.json
  def update
    respond_to do |format|
      if @parking_restriction.update(parking_restriction_params)
        format.html { redirect_to @parking_restriction, notice: 'Parking restriction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parking_restriction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_restrictions/1
  # DELETE /parking_restrictions/1.json
  def destroy
    @parking_restriction.destroy
    respond_to do |format|
      format.html { redirect_to parking_restrictions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_restriction
      @parking_restriction = ParkingRestriction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_restriction_params
      params.require(:parking_restriction).permit(:parking_spot_id, :cost_per_hour, :beg_time_restriction, :end_time_restriction, :time_limit_hour, :time_limit_min, :active_monday, :active_tuesday, :active_wednesday, :active_thursday, :active_friday, :active_saturday, :active_sunday)
    end
end

app/controllers/parking_spots_controller.rb
class ParkingSpotsController < ApplicationController
  before_action :set_parking_spot, only: [:show, :edit, :update, :destroy]

  # GET /parking_spots
  # GET /parking_spots.json
  def index
    @parking_spots = ParkingSpot.all
  end

  # GET /parking_spots/1
  # GET /parking_spots/1.json
  def show
  end

  # GET /parking_spots/new
  def new
    @parking_spot = ParkingSpot.new
  end

  # GET /parking_spots/1/edit
  def edit
  end

  # POST /parking_spots
  # POST /parking_spots.json
  def create
    @parking_spot = ParkingSpot.new(parking_spot_params)

    respond_to do |format|
      if @parking_spot.save
        format.html { redirect_to @parking_spot, notice: 'Parking spot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parking_spot }
      else
        format.html { render action: 'new' }
        format.json { render json: @parking_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_spots/1
  # PATCH/PUT /parking_spots/1.json
  def update
    respond_to do |format|
      if @parking_spot.update(parking_spot_params)
        format.html { redirect_to @parking_spot, notice: 'Parking spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parking_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_spots/1
  # DELETE /parking_spots/1.json
  def destroy
    @parking_spot.destroy
    respond_to do |format|
      format.html { redirect_to parking_spots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_spot
      @parking_spot = ParkingSpot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_spot_params
      params.require(:parking_spot).permit(:latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parking_restrictions_helper.rb
module ParkingRestrictionsHelper
end

app/helpers/parking_spot_helper.rb
module ParkingSpotHelper
end

app/helpers/parking_spots_helper.rb
module ParkingSpotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreetApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parking_restrictions/_form.html.erb
<%= form_for(@parking_restriction) do |f| %>
  <% if @parking_restriction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking_restriction.errors.count, "error") %> prohibited this parking_restriction from being saved:</h2>

      <ul>
      <% @parking_restriction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parking_spot_id %><br>
    <%= f.number_field :parking_spot_id %>
  </div>
  <div class="field">
    <%= f.label :cost_per_hour %><br>
    <%= f.text_field :cost_per_hour %>
  </div>
  <div class="field">
    <%= f.label :beg_time_restriction %><br>
    <%= f.text_field :beg_time_restriction %>
  </div>
  <div class="field">
    <%= f.label :end_time_restriction %><br>
    <%= f.text_field :end_time_restriction %>
  </div>
  <div class="field">
    <%= f.label :time_limit %><br>
    <%= f.number_field :time_limit %>
  </div>
  <div class="field">
    <%= f.label :days_active %><br>
    <%= f.check_box :days_active %><br>
    <%= f.check_box :days_active %><br>
    <%= f.check_box :days_active %><br>
    <%= f.check_box :days_active %><br>
    <%= f.check_box :days_active %><br>
    <%= f.check_box :days_active %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parking_restrictions/edit.html.erb
<h1>Editing parking_restriction</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking_restriction %> |
<%= link_to 'Back', parking_restrictions_path %>

app/views/parking_restrictions/index.html.erb
<h1>Listing parking_restrictions</h1>

<table>
  <thead>
    <tr>
      <th>Parking spot</th>
      <th>Cost per hour</th>
      <th>Beg time restriction</th>
      <th>End time restriction</th>
      <th>Time limit hour</th>
      <th>Time limit min</th>
      <th>Active monday</th>
      <th>Active tuesday</th>
      <th>Active wednesday</th>
      <th>Active thursday</th>
      <th>Active friday</th>
      <th>Active saturday</th>
      <th>Active sunday</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parking_restrictions.each do |parking_restriction| %>
      <tr>
        <td><%= parking_restriction.parking_spot_id %></td>
        <td><%= parking_restriction.cost_per_hour %></td>
        <td><%= parking_restriction.beg_time_restriction %></td>
        <td><%= parking_restriction.end_time_restriction %></td>
        <td><%= parking_restriction.time_limit %></td>
        <td><%= link_to 'Show', parking_restriction %></td>
        <td><%= link_to 'Edit', edit_parking_restriction_path(parking_restriction) %></td>
        <td><%= link_to 'Destroy', parking_restriction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parking restriction', new_parking_restriction_path %>

app/views/parking_restrictions/new.html.erb
<h1>New parking_restriction</h1>

<%= render 'form' %>

<%= link_to 'Back', parking_restrictions_path %>

app/views/parking_restrictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parking spot:</strong>
  <%= @parking_restriction.parking_spot_id %>
</p>

<p>
  <strong>Cost per hour:</strong>
  <%= @parking_restriction.cost_per_hour %>
</p>

<p>
  <strong>Beg time restriction:</strong>
  <%= @parking_restriction.beg_time_restriction %>
</p>

<p>
  <strong>End time restriction:</strong>
  <%= @parking_restriction.end_time_restriction %>
</p>

<p>
  <strong>Time limit hour:</strong>
  <%= @parking_restriction.time_limit %>
</p>


<%@parking_restriction.days_active.each do |day| %>
<p>
  <strong>Day</strong>
  <%= day %>
</p>
<% end %>



<%= link_to 'Edit', edit_parking_restriction_path(@parking_restriction) %> |
<%= link_to 'Back', parking_restrictions_path %>

app/views/parking_spots/_form.html.erb
<%= form_for(@parking_spot) do |f| %>
  <% if @parking_spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking_spot.errors.count, "error") %> prohibited this parking_spot from being saved:</h2>

      <ul>
      <% @parking_spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parking_spots/edit.html.erb
<h1>Editing parking_spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking_spot %> |
<%= link_to 'Back', parking_spots_path %>

app/views/parking_spots/index.html.erb
<h1>Listing parking_spots</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parking_spots.each do |parking_spot| %>
      <tr>
        <td><%= parking_spot.latitude %></td>
        <td><%= parking_spot.longitude %></td>
        <td><%= link_to 'Show', parking_spot %></td>
        <td><%= link_to 'Edit', edit_parking_spot_path(parking_spot) %></td>
        <td><%= link_to 'Destroy', parking_spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parking spot', new_parking_spot_path %>

app/views/parking_spots/new.html.erb
<h1>New parking_spot</h1>

<%= render 'form' %>

<%= link_to 'Back', parking_spots_path %>

app/views/parking_spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @parking_spot.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @parking_spot.longitude %>
</p>

<%= link_to 'Edit', edit_parking_spot_path(@parking_spot) %> |
<%= link_to 'Back', parking_spots_path %>